name: Collect Microsoft Reward Points

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '47 1,12 * * *'

jobs:
  collect-microsoft-reward-points:
    runs-on: ubuntu-latest

    steps:
    - name: Check out
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: ${{ runner.os }}-pip-
          
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        sudo apt-get install -y microsoft-edge-stable
        
    - name: Run Reward.py for Acc1
      run: python -u Reward.py bhowmickdip8@gmail.com School@123

    - name: Run Reward.py for Acc2
      run: python -u Reward.py bhowmikitzraj6@gmail.com Raj@080204
