name: Collect Microsoft Reward Points

on:
  schedule:
    - cron: '30 21 * * *'

jobs:
  collect-microsoft-reward-points:
    runs-on: ubuntu-latest

    steps:
    - name: Check out
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: ${{ runner.os }}-pip-
          
    # - name: Cache User Data
    #   uses: actions/cache@v3
    #   with:
    #     path: user_data
    #     key: ${{ runner.os }}-user-${{ hashFiles('**/cache.txt') }}
    #     restore-keys: ${{ runner.os }}-user-

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        sudo apt-get install -y microsoft-edge-stable
        
    - name: Run Reward.py
      run: python -u Reward.py

    - name: Set up Git
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@users.noreply.github.com"

    - name: Commit changes
      run: |
        if git diff --quiet HEAD -- cache.txt
        then
          echo "Skip cache.txt update, as it is still valid."
        else
          git add cache.txt
          git commit -m "Update cache.txt"
          git push origin master
        fi
        
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
