name: Collect Microsoft Reward Points

on:
  schedule:
    - cron: '40 10 * * *'

jobs:
  selenium-edge:
    runs-on: ubuntu-latest

    steps:
    - name: Check out
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Cache files
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: microsoft-reward-points-files-cache
        restore-keys: microsoft-reward-points-files-cache

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        sudo apt-get install -y microsoft-edge-stable
        
    - name: Run Reward.py
      run: python Reward.py
