name: Collect Microsoft Reward Points

on:
  workflow_dispatch:

jobs:
  selenium-edge:
    runs-on: ubuntu-latest

    steps:
    - name: Check out
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: ${{ runner.os }}-pip-
        
    - name: Set up apt cache
      uses: actions/cache@v3
      with:
        path: /var/cache/apt/archives/*.deb
        key: ${{ runner.os }}-apt-${{ hashFiles('**/apt-get-install*.txt') }}
        restore-keys: ${{ runner.os }}-apt-
          
    - name: Cache User Data
      uses: actions/cache@v3
      with:
        path: user_data
        key: ${{ runner.os }}-user-${{ hashFiles('**/cache.txt') }}
        restore-keys: ${{ runner.os }}-user-

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        sudo apt-get install -y microsoft-edge-stable
        
    - name: Run Reward.py
      run: python -u Reward.py

    - name: Set up Git
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@users.noreply.github.com"

    - name: Commit changes
      run: |
        git add cache.txt
        git commit -m "Update cache.txt" || echo "No changes to commit"
        git push origin master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
